id = "noted"
name = "Noted"
version = "0.1.0"
schema_version = 1
authors = ["Valery Sergeeva <valeriia.sergeeva@gmail.com>"]
description = "Obsidian-flavored Markdown for Zed — wikilinks, tags, callouts, hover previews, diagnostics, live preview, and smart navigation for your MD knowledge base."
repository = "https://github.com/sergeevalera/noted"

[grammars.noted]
repository = "https://github.com/sergeevalera/tree-sitter-noted"
rev = "66d11f2baa019ea78891c2198137aba62ef3d867"

[language_servers.noted-lsp]
name = "Noted LSP"
languages = ["Noted Markdown"]
