name = "Noted Markdown"
grammar = "noted"
path_suffixes = ["md", "markdown"]
line_comments = []
word_characters = ["-"]

[[brackets]]
start = "[["
end = "]]"
close = true
newline = false

[[brackets]]
start = "["
end = "]"
close = false
newline = false

[[brackets]]
start = "("
end = ")"
close = true
newline = false

[[brackets]]
start = "**"
end = "**"
close = true
newline = false

[[brackets]]
start = "*"
end = "*"
close = true
newline = false

[[brackets]]
start = "`"
end = "`"
close = true
newline = false
